### ISSUE TITLE
📚 Revamping Helix docs

### ISSUE THREAD

**Issue by Emcho0** [biomejs/website#1919]
### Documentation URL

https://biomejs.dev/guides/editors/third-party-extensions/#helix

### Description

Issue is that there should be a roots parameter for checking the biome.json file for changes to happen and for the linter to partially work. In the current biome version it will format to adapt the changes to formatter sections like indents and its traits (width and so on).

```toml
# Biome formatter config
[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [
    { name = "typescript-language-server", except-features = ["format"] },
    "biome"
]
auto-format = true
formatter = { command = "bash", args = ["biome check --write"] }

[[language]]
name = "typescript"
language-servers = [
    { name = "typescript-language-server", except-features = ["format"] },
    "biome"
]
auto-format = trueformatter = { command = "bash", args = ["biome check --write"] }
[[language]]
name = "tsx"
auto-format = true
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [
    { name = "typescript-language-server", except-features = ["format"] },
    "biome"
]
formatter = { command = "bash", args = ["biome check --write"] }
[[language]]
name = "jsx"
roots = ["biome.json", "biome.jsonc", "package.json"]
auto-format = true
language-servers = [
    { name = "typescript-language-server", except-features = ["format"] },
    "biome"
]
formatter = { command = "bash", args = ["biome check --write"] }
[[language]]
name = "json"
auto-format = true
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
```

### Expectations

My expectations are that when I format on save, it has to check the biome.json file correctly to fix the unused imports, to organize them in the order that they are specified. In short, making sure that the biome.json is correctly implemented for helix without any additional hassle.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Thank you for opening this. Feel free to send a PR! I would create two paragraphs:
- set Biome globally (it uses the current settings I suppose)
- set Biome by project, which I think is the addition of `roots`

Also, I would reduce the configuration to just one language, e.g. `"javascript"`, and then add a new paragraph that explains how to set up Biome for another language, e.g. `javascript`/`css`/`json` with another language server.


What do you think?

**Comment by Emcho0** [comment]
But also can we add the command for running the biome lsp without the cli (meaning to use the package executor for each javascript runtime that is supported). This is not a bad suggestion by any means. This is the example for using bunx, I don't know if some js runtimes like deno have package executor line npx or similar.
```toml
# Remove the bunx command if you want to use the biome cli instead
[language-server]
biome = { command = "bunx", args = ["biome","lsp-proxy"] }

[[language]]
name = "javascript"
# Uncomment this line if you want to use it inside of a project
# roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [
    { name = "typescript-language-server", except-features = ["format"] },
    "biome"
]
auto-format = true
formatter = { command = "bunx", args = ["biome","check","--write", "--stdin-file-path","app.js"] }
```
